# Generated by Django 5.1.15 on 2026-09-09 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('reference_battery_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Nominal usable battery capacity for degradation tracking.', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'vin'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_trip_id', models.CharField(blank=True, max_length=64, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('distance_miles', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('start_soc_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('end_soc_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('battery_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='dashboard.vehicle')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('odometer_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soc_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_battery_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dashboard.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TripPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('sequence', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='dashboard.trip')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_trip_point_sequence')],
            },
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('source_trip_id__isnull', False)), fields=('vehicle', 'source_trip_id'), name='unique_trip_id_per_vehicle'),
        ),
    ]
