# Generated by Django 5.1.15 on 2026-09-11 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippoint',
            name='heading',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='trippoint',
            name='speed_kph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doors_locked', models.BooleanField(blank=True, null=True)),
                ('door_driver', models.BooleanField(blank=True, null=True)),
                ('door_passenger', models.BooleanField(blank=True, null=True)),
                ('door_rear_left', models.BooleanField(blank=True, null=True)),
                ('door_rear_right', models.BooleanField(blank=True, null=True)),
                ('door_bonnet', models.BooleanField(blank=True, null=True)),
                ('door_boot', models.BooleanField(blank=True, null=True)),
                ('window_driver', models.BooleanField(blank=True, null=True)),
                ('window_passenger', models.BooleanField(blank=True, null=True)),
                ('window_rear_left', models.BooleanField(blank=True, null=True)),
                ('window_rear_right', models.BooleanField(blank=True, null=True)),
                ('window_sun_roof', models.BooleanField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='dashboard.vehicle')),
            ],
        ),
    ]
